# Generated by Django 3.2.3 on 2021-05-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('face_value', models.FloatField()),
                ('appraised_value', models.FloatField()),
                ('notes', models.TextField(max_length=300)),
            ],
        ),
    ]
