# Generated by Django 3.2.2 on 2021-05-19 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='appraised_value',
        ),
        migrations.AlterField(
            model_name='coin',
            name='face_value',
            field=models.FloatField(verbose_name='Face Value'),
        ),
        migrations.CreateModel(
            name='Appraisal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.FloatField()),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coins.coin')),
            ],
        ),
    ]
